runtime: php55

api_version: 1
handlers:
- url: /(.+\.(gif|png|jpg|css|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js)$
  application_readable: true

- url: /.*
  script: index.php

env_variables:
  GOOGLE_STORAGE_BUCKET: "wbt-2-ty-272811.appspot.com"
