-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 16:54:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;
CREATE TABLE IF NOT EXISTS `ci_sessions` (
    `id` varchar(128) NOT NULL,
    `ip_address` varchar(45) NOT NULL ,
    `timestamp` int(10) unsigned DEFAULT 0 NOT NULL,
    `data` blob NOT NULL,
    KEY `ci_sessions_timestamp` (`timestamp`)

);
ALTER TABLE ci_sessions ADD PRIMARY KEY (id);
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `u_id` INT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `zip` VARCHAR(45) NULL,
  `building` VARCHAR(45) NULL,
  `is_active` INT(1),
  `role_id` int (1);
  PRIMARY KEY (`u_id`),
  F
  UNIQUE INDEX `username_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`user_role` (
  `id` INT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NULL,

  PRIMARY KEY (`id`)
   )
ENGINE = InnoDB;
CREATE TABLE `mydb`.`user_token`
( `id` INT NOT NULL AUTO_INCREMENT ,
 `email` VARCHAR(45) NOT NULL ,
  `token` VARCHAR(128) NOT NULL ,
  `date_created` INT NOT NULL ,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;

alter TABLE users add FOREIGN KEY (role_id) REFERENCES user_role(id);
alter TABLE user_token add FOREIGN KEY (email) REFERENCES users(email);

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id` INT NULL AUTO_INCREMENT,
  `artist` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NULL,
  `description` VARCHAR(4000) NULL,
  `price` FLOAT(5,2) NULL,
  `q_ty` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `usr_id_idx` (`user_id` ASC) ,
  CONSTRAINT `usr_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prod_in_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prod_in_cart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prod_in_cart` (
  `prod_q_ty` INT NOT NULL,
  `c_id` INT NOT NULL,
  `p_id` INT NOT NULL,
  PRIMARY KEY (`c_id`, `p_id`),
  INDEX `p_id_fk_idx` (`p_id` ASC) ,
  CONSTRAINT `c_id_fk`
    FOREIGN KEY (`c_id`)
    REFERENCES `mydb`.`cart` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `p_id_fk`
    FOREIGN KEY (`p_id`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `id_status` INT NULL,
  `t_time` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_fk_idx` (`id_user` ASC) ,
  INDEX `id_status_fk_idx` (`id_status` ASC) ,
  CONSTRAINT `id_user_fk`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`users` (`u_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_status_fk`
    FOREIGN KEY (`id_status`)
    REFERENCES `mydb`.`status` (`id_status`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trans_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`trans_products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`trans_products` (
  `id_trans` INT NOT NULL,
  `id_prod` INT NOT NULL,
  `num_of_pr` INT NULL,
  `price` FLOAT(5,2) NULL,
  PRIMARY KEY (`id_trans`, `id_prod`),
  INDEX `id_prod_fk_idx` (`id_prod` ASC) ,
  CONSTRAINT `id_trans_fk`
    FOREIGN KEY (`id_trans`)
    REFERENCES `mydb`.`transaction` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `id_prod_fk`
    FOREIGN KEY (`id_prod`)
    REFERENCES `mydb`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
